name: Actualizar Lista M3U

on:
  schedule:
    - cron: '*/5 * * * *'  # Se ejecuta cada 2 horas
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub

permissions:
  contents: write           # Permiso necesario para guardar el .m3u en el repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Ejecutar script de conversión
      run: python generate_m3u.py

    - name: Commit y push del archivo M3U
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add eventos.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update eventos.m3u" && git push)
